build:
  go:
    image: golang:1.6-alpine
    commands:
      - go get -t -d
      - go test -cover ./...
  python:
    image: python:2-alpine
    commands:
      - pip install .
      - python client_test.py
