// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package essenceauth is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	Empty
	LoginRequest
	UserLogin
	App
	AppList
	AppChange
	AppUserRequest
	Membership
	Group
	GroupList
	GroupChange
	Permission
	PermissionValue
	User
	UserList
	UserChange
*/
package essenceauth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Login through the API.
type LoginRequest struct {
	ID       string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// A login response from the API.
type UserLogin struct {
	Email   string `protobuf:"bytes,1,opt,name=Email,json=email" json:"Email,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	Picture string `protobuf:"bytes,3,opt,name=Picture,json=picture" json:"Picture,omitempty"`
	JWT     string `protobuf:"bytes,4,opt,name=JWT,json=jWT" json:"JWT,omitempty"`
}

func (m *UserLogin) Reset()                    { *m = UserLogin{} }
func (m *UserLogin) String() string            { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()               {}
func (*UserLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserLogin) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserLogin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserLogin) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *UserLogin) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

type App struct {
	ID          string        `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Key         string        `protobuf:"bytes,2,opt,name=Key,json=key" json:"Key,omitempty"`
	Name        string        `protobuf:"bytes,3,opt,name=Name,json=name" json:"Name,omitempty"`
	Permissions []*Permission `protobuf:"bytes,4,rep,name=Permissions,json=permissions" json:"Permissions,omitempty"`
}

func (m *App) Reset()                    { *m = App{} }
func (m *App) String() string            { return proto.CompactTextString(m) }
func (*App) ProtoMessage()               {}
func (*App) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *App) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *App) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type AppList struct {
	Apps []*App `protobuf:"bytes,1,rep,name=Apps,json=apps" json:"Apps,omitempty"`
}

func (m *AppList) Reset()                    { *m = AppList{} }
func (m *AppList) String() string            { return proto.CompactTextString(m) }
func (*AppList) ProtoMessage()               {}
func (*AppList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AppList) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

// AppChange is used to update an applications name and admins.
type AppChange struct {
	ID      string   `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	Members []string `protobuf:"bytes,3,rep,name=Members,json=members" json:"Members,omitempty"`
}

func (m *AppChange) Reset()                    { *m = AppChange{} }
func (m *AppChange) String() string            { return proto.CompactTextString(m) }
func (*AppChange) ProtoMessage()               {}
func (*AppChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AppChange) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AppChange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppChange) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

// AppUserRequest is used to fetch info about a user by an application.
type AppUserRequest struct {
	ID   string   `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Keys []string `protobuf:"bytes,2,rep,name=Keys,json=keys" json:"Keys,omitempty"`
	JWT  string   `protobuf:"bytes,3,opt,name=JWT,json=jWT" json:"JWT,omitempty"`
}

func (m *AppUserRequest) Reset()                    { *m = AppUserRequest{} }
func (m *AppUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AppUserRequest) ProtoMessage()               {}
func (*AppUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AppUserRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AppUserRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *AppUserRequest) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

// Membership provides a list of members and outdsiders for an App or Group.
type Membership struct {
	Members   []string `protobuf:"bytes,1,rep,name=Members,json=members" json:"Members,omitempty"`
	Outsiders []string `protobuf:"bytes,2,rep,name=Outsiders,json=outsiders" json:"Outsiders,omitempty"`
}

func (m *Membership) Reset()                    { *m = Membership{} }
func (m *Membership) String() string            { return proto.CompactTextString(m) }
func (*Membership) ProtoMessage()               {}
func (*Membership) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Membership) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Membership) GetOutsiders() []string {
	if m != nil {
		return m.Outsiders
	}
	return nil
}

type Group struct {
	ID    int32  `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	Auto  bool   `protobuf:"varint,3,opt,name=Auto,json=auto" json:"Auto,omitempty"`
	Owner string `protobuf:"bytes,4,opt,name=Owner,json=owner" json:"Owner,omitempty"`
	Apps  []*App `protobuf:"bytes,5,rep,name=Apps,json=apps" json:"Apps,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Group) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetAuto() bool {
	if m != nil {
		return m.Auto
	}
	return false
}

func (m *Group) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Group) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type GroupList struct {
	Groups []*Group `protobuf:"bytes,1,rep,name=Groups,json=groups" json:"Groups,omitempty"`
}

func (m *GroupList) Reset()                    { *m = GroupList{} }
func (m *GroupList) String() string            { return proto.CompactTextString(m) }
func (*GroupList) ProtoMessage()               {}
func (*GroupList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GroupList) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

// GroupChange is used to update a groups name, auto status, memebers and application permissions.
type GroupChange struct {
	ID      int32    `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	Auto    bool     `protobuf:"varint,3,opt,name=Auto,json=auto" json:"Auto,omitempty"`
	Members []string `protobuf:"bytes,4,rep,name=Members,json=members" json:"Members,omitempty"`
	Apps    []*App   `protobuf:"bytes,5,rep,name=Apps,json=apps" json:"Apps,omitempty"`
}

func (m *GroupChange) Reset()                    { *m = GroupChange{} }
func (m *GroupChange) String() string            { return proto.CompactTextString(m) }
func (*GroupChange) ProtoMessage()               {}
func (*GroupChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GroupChange) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GroupChange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupChange) GetAuto() bool {
	if m != nil {
		return m.Auto
	}
	return false
}

func (m *GroupChange) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *GroupChange) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type Permission struct {
	ID     string             `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Name   string             `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	Values []*PermissionValue `protobuf:"bytes,3,rep,name=Values,json=values" json:"Values,omitempty"`
}

func (m *Permission) Reset()                    { *m = Permission{} }
func (m *Permission) String() string            { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()               {}
func (*Permission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Permission) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Permission) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Permission) GetValues() []*PermissionValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type PermissionValue struct {
	Key   string `protobuf:"bytes,1,opt,name=Key,json=key" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,json=value" json:"Value,omitempty"`
}

func (m *PermissionValue) Reset()                    { *m = PermissionValue{} }
func (m *PermissionValue) String() string            { return proto.CompactTextString(m) }
func (*PermissionValue) ProtoMessage()               {}
func (*PermissionValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PermissionValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PermissionValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type User struct {
	Email   string `protobuf:"bytes,1,opt,name=Email,json=email" json:"Email,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	Picture string `protobuf:"bytes,3,opt,name=Picture,json=picture" json:"Picture,omitempty"`
	Admin   bool   `protobuf:"varint,4,opt,name=Admin,json=admin" json:"Admin,omitempty"`
	Apps    []*App `protobuf:"bytes,5,rep,name=Apps,json=apps" json:"Apps,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *User) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *User) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type UserList struct {
	Users []*User `protobuf:"bytes,1,rep,name=Users,json=users" json:"Users,omitempty"`
}

func (m *UserList) Reset()                    { *m = UserList{} }
func (m *UserList) String() string            { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()               {}
func (*UserList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UserList) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// A user change request or response.
type UserChange struct {
	Email    string `protobuf:"bytes,1,opt,name=Email,json=email" json:"Email,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *UserChange) Reset()                    { *m = UserChange{} }
func (m *UserChange) String() string            { return proto.CompactTextString(m) }
func (*UserChange) ProtoMessage()               {}
func (*UserChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UserChange) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserChange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserChange) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "essenceauth.Empty")
	proto.RegisterType((*LoginRequest)(nil), "essenceauth.LoginRequest")
	proto.RegisterType((*UserLogin)(nil), "essenceauth.UserLogin")
	proto.RegisterType((*App)(nil), "essenceauth.App")
	proto.RegisterType((*AppList)(nil), "essenceauth.AppList")
	proto.RegisterType((*AppChange)(nil), "essenceauth.AppChange")
	proto.RegisterType((*AppUserRequest)(nil), "essenceauth.AppUserRequest")
	proto.RegisterType((*Membership)(nil), "essenceauth.Membership")
	proto.RegisterType((*Group)(nil), "essenceauth.Group")
	proto.RegisterType((*GroupList)(nil), "essenceauth.GroupList")
	proto.RegisterType((*GroupChange)(nil), "essenceauth.GroupChange")
	proto.RegisterType((*Permission)(nil), "essenceauth.Permission")
	proto.RegisterType((*PermissionValue)(nil), "essenceauth.PermissionValue")
	proto.RegisterType((*User)(nil), "essenceauth.User")
	proto.RegisterType((*UserList)(nil), "essenceauth.UserList")
	proto.RegisterType((*UserChange)(nil), "essenceauth.UserChange")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EssenceAuth service

type EssenceAuthClient interface {
	// Login.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserLogin, error)
	// Used by an application to fetch information about a user using their JWT.
	AppGetUser(ctx context.Context, in *AppUserRequest, opts ...grpc.CallOption) (*User, error)
	// An application can get info about itself.
	AppGetApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*App, error)
	// Allows an application to provide information about its available permissions.
	// Those permissions can then be given to groups and therefore users.
	AppUpdateApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*App, error)
	ListApps(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AppList, error)
	GetApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*App, error)
	CreateApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*App, error)
	PutApp(ctx context.Context, in *AppChange, opts ...grpc.CallOption) (*App, error)
	DeleteApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*Empty, error)
	GetAppMembers(ctx context.Context, in *App, opts ...grpc.CallOption) (*Membership, error)
	ListGroups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GroupList, error)
	GetGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error)
	CreateGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error)
	PutGroup(ctx context.Context, in *GroupChange, opts ...grpc.CallOption) (*Group, error)
	DeleteGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Empty, error)
	GetGroupMembers(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Membership, error)
	ListUsers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserList, error)
	GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	CreateUser(ctx context.Context, in *UserChange, opts ...grpc.CallOption) (*User, error)
	PutUser(ctx context.Context, in *UserChange, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error)
	ResetUserPassword(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserChange, error)
}

type essenceAuthClient struct {
	cc *grpc.ClientConn
}

func NewEssenceAuthClient(cc *grpc.ClientConn) EssenceAuthClient {
	return &essenceAuthClient{cc}
}

func (c *essenceAuthClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserLogin, error) {
	out := new(UserLogin)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) AppGetUser(ctx context.Context, in *AppUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/AppGetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) AppGetApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/AppGetApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) AppUpdateApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/AppUpdateApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) ListApps(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AppList, error) {
	out := new(AppList)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/ListApps", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) GetApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/GetApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) CreateApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/CreateApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) PutApp(ctx context.Context, in *AppChange, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/PutApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) DeleteApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/DeleteApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) GetAppMembers(ctx context.Context, in *App, opts ...grpc.CallOption) (*Membership, error) {
	out := new(Membership)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/GetAppMembers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) ListGroups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GroupList, error) {
	out := new(GroupList)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/ListGroups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) GetGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/GetGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) CreateGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/CreateGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) PutGroup(ctx context.Context, in *GroupChange, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/PutGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) DeleteGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/DeleteGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) GetGroupMembers(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Membership, error) {
	out := new(Membership)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/GetGroupMembers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) ListUsers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserList, error) {
	out := new(UserList)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) CreateUser(ctx context.Context, in *UserChange, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) PutUser(ctx context.Context, in *UserChange, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/PutUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *essenceAuthClient) ResetUserPassword(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserChange, error) {
	out := new(UserChange)
	err := grpc.Invoke(ctx, "/essenceauth.EssenceAuth/ResetUserPassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EssenceAuth service

type EssenceAuthServer interface {
	// Login.
	Login(context.Context, *LoginRequest) (*UserLogin, error)
	// Used by an application to fetch information about a user using their JWT.
	AppGetUser(context.Context, *AppUserRequest) (*User, error)
	// An application can get info about itself.
	AppGetApp(context.Context, *App) (*App, error)
	// Allows an application to provide information about its available permissions.
	// Those permissions can then be given to groups and therefore users.
	AppUpdateApp(context.Context, *App) (*App, error)
	ListApps(context.Context, *Empty) (*AppList, error)
	GetApp(context.Context, *App) (*App, error)
	CreateApp(context.Context, *App) (*App, error)
	PutApp(context.Context, *AppChange) (*App, error)
	DeleteApp(context.Context, *App) (*Empty, error)
	GetAppMembers(context.Context, *App) (*Membership, error)
	ListGroups(context.Context, *Empty) (*GroupList, error)
	GetGroup(context.Context, *Group) (*Group, error)
	CreateGroup(context.Context, *Group) (*Group, error)
	PutGroup(context.Context, *GroupChange) (*Group, error)
	DeleteGroup(context.Context, *Group) (*Empty, error)
	GetGroupMembers(context.Context, *Group) (*Membership, error)
	ListUsers(context.Context, *Empty) (*UserList, error)
	GetUser(context.Context, *User) (*User, error)
	CreateUser(context.Context, *UserChange) (*User, error)
	PutUser(context.Context, *UserChange) (*User, error)
	DeleteUser(context.Context, *User) (*Empty, error)
	ResetUserPassword(context.Context, *User) (*UserChange, error)
}

func RegisterEssenceAuthServer(s *grpc.Server, srv EssenceAuthServer) {
	s.RegisterService(&_EssenceAuth_serviceDesc, srv)
}

func _EssenceAuth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_AppGetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).AppGetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/AppGetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).AppGetUser(ctx, req.(*AppUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_AppGetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).AppGetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/AppGetApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).AppGetApp(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_AppUpdateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).AppUpdateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/AppUpdateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).AppUpdateApp(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/ListApps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).ListApps(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).GetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/GetApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).GetApp(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).CreateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/CreateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).CreateApp(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_PutApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).PutApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/PutApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).PutApp(ctx, req.(*AppChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_DeleteApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).DeleteApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/DeleteApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).DeleteApp(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_GetAppMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).GetAppMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/GetAppMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).GetAppMembers(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).ListGroups(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).GetGroup(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).CreateGroup(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_PutGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).PutGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/PutGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).PutGroup(ctx, req.(*GroupChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).DeleteGroup(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_GetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).GetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/GetGroupMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).GetGroupMembers(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).ListUsers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).GetUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).CreateUser(ctx, req.(*UserChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_PutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).PutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/PutUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).PutUser(ctx, req.(*UserChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).DeleteUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _EssenceAuth_ResetUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EssenceAuthServer).ResetUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/essenceauth.EssenceAuth/ResetUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EssenceAuthServer).ResetUserPassword(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _EssenceAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "essenceauth.EssenceAuth",
	HandlerType: (*EssenceAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _EssenceAuth_Login_Handler,
		},
		{
			MethodName: "AppGetUser",
			Handler:    _EssenceAuth_AppGetUser_Handler,
		},
		{
			MethodName: "AppGetApp",
			Handler:    _EssenceAuth_AppGetApp_Handler,
		},
		{
			MethodName: "AppUpdateApp",
			Handler:    _EssenceAuth_AppUpdateApp_Handler,
		},
		{
			MethodName: "ListApps",
			Handler:    _EssenceAuth_ListApps_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _EssenceAuth_GetApp_Handler,
		},
		{
			MethodName: "CreateApp",
			Handler:    _EssenceAuth_CreateApp_Handler,
		},
		{
			MethodName: "PutApp",
			Handler:    _EssenceAuth_PutApp_Handler,
		},
		{
			MethodName: "DeleteApp",
			Handler:    _EssenceAuth_DeleteApp_Handler,
		},
		{
			MethodName: "GetAppMembers",
			Handler:    _EssenceAuth_GetAppMembers_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _EssenceAuth_ListGroups_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _EssenceAuth_GetGroup_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _EssenceAuth_CreateGroup_Handler,
		},
		{
			MethodName: "PutGroup",
			Handler:    _EssenceAuth_PutGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _EssenceAuth_DeleteGroup_Handler,
		},
		{
			MethodName: "GetGroupMembers",
			Handler:    _EssenceAuth_GetGroupMembers_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _EssenceAuth_ListUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _EssenceAuth_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _EssenceAuth_CreateUser_Handler,
		},
		{
			MethodName: "PutUser",
			Handler:    _EssenceAuth_PutUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _EssenceAuth_DeleteUser_Handler,
		},
		{
			MethodName: "ResetUserPassword",
			Handler:    _EssenceAuth_ResetUserPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1056 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x97, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xc7, 0x21, 0x93, 0xd4, 0xc7, 0xc8, 0xb1, 0xe5, 0x8d, 0x2c, 0xd1, 0xb4, 0xdc, 0x18, 0xdb,
	0x16, 0x0d, 0x74, 0xb0, 0x00, 0xa7, 0x40, 0x91, 0xdc, 0x88, 0x28, 0x35, 0xec, 0xb8, 0xb1, 0x4a,
	0x28, 0x0d, 0xda, 0x4b, 0xc1, 0xc4, 0x1b, 0x99, 0x8d, 0x44, 0x6e, 0xf9, 0xe1, 0x40, 0x30, 0x72,
	0x29, 0xd0, 0xbe, 0x40, 0x1f, 0xad, 0xaf, 0xd0, 0x43, 0x1f, 0xa3, 0xd8, 0x59, 0xd2, 0x12, 0xc5,
	0x65, 0x21, 0x01, 0xbd, 0x69, 0xbf, 0x7e, 0x3b, 0xf3, 0x9f, 0xd9, 0x3f, 0x21, 0x00, 0x37, 0x89,
	0x6f, 0x4e, 0x78, 0x18, 0xc4, 0x01, 0x69, 0xb2, 0x28, 0x62, 0xfe, 0x3b, 0x26, 0xa6, 0xac, 0xde,
	0x24, 0x08, 0x26, 0x53, 0x36, 0x70, 0xb9, 0x37, 0x70, 0x7d, 0x3f, 0x88, 0xdd, 0xd8, 0x0b, 0xfc,
	0x48, 0x6e, 0xa5, 0x35, 0x30, 0x5e, 0xcc, 0x78, 0x3c, 0xa7, 0xcf, 0x60, 0xfb, 0x32, 0x98, 0x78,
	0xbe, 0xc3, 0x7e, 0x4d, 0x58, 0x14, 0x93, 0x1d, 0xd8, 0x3a, 0x1f, 0x9a, 0x95, 0xe3, 0xca, 0xe3,
	0x86, 0xb3, 0xe5, 0x0d, 0x89, 0x05, 0xf5, 0x91, 0x1b, 0x45, 0x1f, 0x83, 0xf0, 0xda, 0xdc, 0xc2,
	0xd9, 0x3a, 0x4f, 0xc7, 0xd4, 0x85, 0xc6, 0xeb, 0x88, 0x85, 0x78, 0x9e, 0xb4, 0x05, 0xd1, 0xf5,
	0xa6, 0xe9, 0x59, 0x83, 0x89, 0x01, 0x21, 0xa0, 0xbf, 0x72, 0x67, 0x2c, 0x3d, 0xaa, 0xfb, 0xee,
	0x8c, 0x11, 0x13, 0x6a, 0x23, 0xef, 0x5d, 0x9c, 0x84, 0xcc, 0xd4, 0x70, 0xba, 0xc6, 0xe5, 0x90,
	0xb4, 0x40, 0xbb, 0x78, 0x33, 0x36, 0x75, 0x9c, 0xd5, 0x7e, 0x79, 0x33, 0xa6, 0xb7, 0xa0, 0xd9,
	0x9c, 0x17, 0xa2, 0x6a, 0x81, 0xf6, 0x92, 0xcd, 0x53, 0xaa, 0xf6, 0x81, 0xcd, 0xef, 0x2f, 0xd2,
	0x96, 0x2e, 0x7a, 0x0a, 0xcd, 0x11, 0x0b, 0x67, 0x5e, 0x14, 0x89, 0xcc, 0x4d, 0xfd, 0x58, 0x7b,
	0xdc, 0x3c, 0xed, 0x9e, 0x2c, 0xa9, 0x74, 0xb2, 0x58, 0x77, 0x9a, 0x7c, 0xb1, 0x97, 0x0e, 0xa0,
	0x66, 0x73, 0x7e, 0xe9, 0x45, 0x31, 0xf9, 0x02, 0x74, 0x9b, 0xf3, 0xc8, 0xac, 0xe0, 0xf1, 0x56,
	0xee, 0xb8, 0xcd, 0xb9, 0xa3, 0xbb, 0x9c, 0x47, 0xf4, 0x1c, 0x1a, 0x36, 0xe7, 0xcf, 0x6f, 0x5c,
	0x7f, 0xc2, 0x0a, 0xe1, 0x96, 0xa8, 0xf0, 0x1d, 0x9b, 0xbd, 0x65, 0x61, 0x64, 0x6a, 0xc7, 0x9a,
	0x50, 0x61, 0x26, 0x87, 0xf4, 0x5b, 0xd8, 0xb1, 0x39, 0x17, 0xca, 0x96, 0x15, 0x85, 0x80, 0xfe,
	0x92, 0xcd, 0x23, 0x73, 0x0b, 0x0f, 0xea, 0x1f, 0xd8, 0x3c, 0xca, 0xb4, 0xd3, 0x16, 0xda, 0x0d,
	0x01, 0xd2, 0x1b, 0x6e, 0x3c, 0xbe, 0x7c, 0x5f, 0x25, 0x77, 0x1f, 0xe9, 0x41, 0xe3, 0x2a, 0x89,
	0x23, 0xef, 0x5a, 0xac, 0x49, 0x64, 0x23, 0xc8, 0x26, 0xe8, 0x1d, 0x18, 0x67, 0x61, 0x90, 0x2c,
	0xd7, 0xc0, 0x28, 0x4d, 0x8a, 0x80, 0x6e, 0x27, 0x71, 0x80, 0x51, 0xd4, 0x1d, 0xdd, 0x4d, 0xe2,
	0x40, 0x34, 0xc6, 0xd5, 0x47, 0x9f, 0x85, 0x69, 0x59, 0x8d, 0x40, 0x0c, 0xee, 0x55, 0x35, 0xfe,
	0x53, 0xd5, 0x6f, 0xa0, 0x81, 0x97, 0x63, 0x21, 0xfa, 0x50, 0xc5, 0x41, 0x56, 0x0a, 0x92, 0x3b,
	0x84, 0x4b, 0x4e, 0x75, 0x82, 0x3b, 0xe8, 0xef, 0x15, 0x68, 0xe2, 0x4c, 0xa1, 0x22, 0x9b, 0x05,
	0xbf, 0xa4, 0x9a, 0x9e, 0x57, 0x6d, 0xbd, 0x04, 0xde, 0x03, 0x2c, 0x5a, 0x6c, 0xad, 0xbe, 0xf8,
	0x1a, 0xaa, 0x3f, 0xb8, 0xd3, 0x84, 0xc9, 0xb6, 0x68, 0x9e, 0xf6, 0x4a, 0xfa, 0x15, 0x37, 0x39,
	0xd5, 0x5b, 0xdc, 0x4b, 0x9f, 0xc2, 0xee, 0xca, 0x52, 0xf6, 0x46, 0x2a, 0x8b, 0x37, 0xd2, 0x06,
	0x03, 0x97, 0xd2, 0xfb, 0x0c, 0x3c, 0x4b, 0xff, 0xa8, 0x80, 0x2e, 0x9a, 0xed, 0x7f, 0x79, 0xc1,
	0x6d, 0x30, 0xec, 0xeb, 0x99, 0xe7, 0x63, 0xb1, 0xeb, 0x8e, 0xe1, 0x8a, 0xc1, 0x9a, 0x5a, 0x3d,
	0x81, 0x3a, 0xda, 0x89, 0xa8, 0xf5, 0x57, 0x60, 0x88, 0xdf, 0x59, 0xa9, 0xf7, 0x72, 0x47, 0xf0,
	0x69, 0x18, 0x89, 0x58, 0xa7, 0x0e, 0x80, 0x18, 0xa6, 0x65, 0x5e, 0x3f, 0x85, 0x65, 0x5f, 0xd3,
	0xf2, 0xbe, 0x76, 0xfa, 0xcf, 0x0e, 0x34, 0x5f, 0xc8, 0xfb, 0xec, 0x24, 0xbe, 0x21, 0x63, 0x30,
	0xa4, 0xc7, 0x1d, 0xe4, 0xc2, 0x58, 0xf6, 0x4d, 0xab, 0x53, 0x88, 0x10, 0x97, 0xa9, 0xf9, 0xdb,
	0x5f, 0x7f, 0xff, 0xb9, 0x45, 0xe8, 0x03, 0x34, 0xe2, 0xdb, 0xd3, 0xc1, 0x54, 0x4c, 0x3f, 0xab,
	0xf4, 0xc9, 0x6b, 0x00, 0x9b, 0xf3, 0x33, 0x16, 0xa3, 0xf8, 0x87, 0xab, 0xa2, 0x2c, 0xbd, 0x7f,
	0xab, 0x98, 0x3e, 0xed, 0x22, 0x77, 0x8f, 0x6e, 0x67, 0x5c, 0x21, 0x87, 0xc0, 0x5e, 0xa0, 0x11,
	0x9d, 0xb1, 0x58, 0xf8, 0x66, 0x41, 0x6a, 0xab, 0x30, 0x43, 0x0f, 0x90, 0xf4, 0x90, 0xec, 0x65,
	0x24, 0x51, 0x8c, 0xc1, 0xdd, 0xf9, 0xf0, 0x13, 0x19, 0xc1, 0xb6, 0x88, 0x84, 0x5f, 0xbb, 0x31,
	0x5b, 0x17, 0xd7, 0x43, 0x5c, 0x87, 0x16, 0x71, 0x22, 0xba, 0x4b, 0xa8, 0x8b, 0xfa, 0x8a, 0x6e,
	0x20, 0xf9, 0xf7, 0x8b, 0x9f, 0x23, 0xab, 0xbd, 0xca, 0x13, 0xbb, 0x69, 0x07, 0x99, 0x2d, 0xb2,
	0x73, 0xcf, 0x44, 0x2a, 0x39, 0x87, 0xea, 0x06, 0x89, 0x1e, 0x22, 0x65, 0x9f, 0x3c, 0xcc, 0x53,
	0x64, 0xaa, 0x17, 0xd0, 0x78, 0x1e, 0xb2, 0x0d, 0xf2, 0x4c, 0x65, 0xa3, 0x2b, 0x31, 0x89, 0x24,
	0x1d, 0xa8, 0x8e, 0x12, 0x0c, 0xab, 0xb3, 0x7a, 0x4c, 0xf6, 0xa9, 0x02, 0xf7, 0x19, 0xe2, 0x4c,
	0x4b, 0x15, 0x9c, 0x60, 0xbe, 0x82, 0xc6, 0x90, 0x4d, 0x59, 0x59, 0x7c, 0x0a, 0x2d, 0xb3, 0x7c,
	0xfb, 0xca, 0x7c, 0x7f, 0x86, 0x07, 0x52, 0xba, 0xd4, 0xde, 0x14, 0xcc, 0xfc, 0x97, 0x72, 0xf1,
	0x29, 0xa1, 0x9f, 0x23, 0xf8, 0x88, 0x1c, 0x2a, 0xc0, 0x83, 0xcc, 0x1f, 0x1d, 0x00, 0x51, 0x3b,
	0xe9, 0xd8, 0xca, 0x5a, 0x77, 0x8a, 0xfe, 0x8d, 0xd5, 0x4e, 0x9f, 0x0c, 0x69, 0x2d, 0xf0, 0xd2,
	0xd5, 0xc9, 0xf7, 0x50, 0x3f, 0x63, 0x12, 0x49, 0x14, 0xee, 0x6f, 0x29, 0xe6, 0xe8, 0x11, 0xd2,
	0xba, 0x64, 0x7f, 0x95, 0x26, 0x75, 0x70, 0xa0, 0x29, 0xeb, 0xbe, 0x19, 0x35, 0xd5, 0x96, 0x16,
	0x62, 0x14, 0xb5, 0xfa, 0x09, 0xea, 0xa3, 0x24, 0x0d, 0xd3, 0x2c, 0x1e, 0x4e, 0x7b, 0x40, 0x85,
	0x3d, 0x46, 0xac, 0x65, 0xa9, 0x83, 0x15, 0xec, 0x31, 0x34, 0x65, 0x1f, 0xac, 0x1b, 0xaf, 0xec,
	0x85, 0x54, 0x85, 0x7e, 0x89, 0x0a, 0x0c, 0x76, 0x33, 0x61, 0xb3, 0x7e, 0x50, 0x91, 0x4b, 0x3b,
	0xe2, 0x4b, 0xc4, 0x3f, 0x22, 0x47, 0x4a, 0xfc, 0x7d, 0x4f, 0x5c, 0x41, 0x43, 0x54, 0x18, 0x9d,
	0x5d, 0xd9, 0x12, 0xfb, 0x45, 0x17, 0x15, 0x1d, 0x91, 0x9a, 0x1d, 0xd9, 0x5d, 0xe0, 0xd1, 0xfd,
	0xc9, 0x08, 0x6a, 0x99, 0x81, 0x16, 0x3d, 0x52, 0x65, 0x9b, 0x8f, 0x90, 0x74, 0x40, 0xba, 0x2b,
	0xa4, 0xc1, 0x1d, 0x7e, 0x37, 0x3e, 0x91, 0x31, 0x80, 0xec, 0x07, 0x84, 0x76, 0x0b, 0x84, 0xb4,
	0x78, 0x0a, 0xb4, 0x85, 0xe8, 0x36, 0x5d, 0x0d, 0x52, 0x54, 0xed, 0x47, 0xa8, 0x8d, 0x92, 0x78,
	0x63, 0x24, 0x45, 0x64, 0xcf, 0x2a, 0x8b, 0x56, 0x36, 0x04, 0xc8, 0x86, 0x28, 0x53, 0x41, 0xd5,
	0x0e, 0xa9, 0x0c, 0xfd, 0x52, 0x19, 0xde, 0xc3, 0x9e, 0xc3, 0x22, 0x29, 0x6d, 0xf6, 0x9d, 0x54,
	0xc1, 0xcb, 0xb2, 0xc9, 0x3a, 0x82, 0x1e, 0x95, 0xdc, 0x30, 0x08, 0x05, 0xfe, 0x6d, 0x15, 0xff,
	0x8e, 0x3c, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x2b, 0xea, 0x9a, 0xc7, 0x0c, 0x00, 0x00,
}
